version: '3'
services:
  docker-mysql:
    restart: always
    container_name: docker-mysql
    image: "mysql/mysql-server:5.7"
    env_file: .env
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PWD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PWD}
    volumes:
      - ./sql:/docker-entrypoint-initdb.d

    ports:
      - "3306:3306"
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=root--execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10

  docker-springboot:
    restart: on-failure
    container_name: flightboot
    image: flightboot:latest
    build:
      context: .
      dockerfile: Dockerfile
#    user: root
    env_file: .env
    expose:
      - "8080"
    ports:
      - ${HTTP_PORT}:8080
    environment:
      WAIT_HOSTS: mysql:3306
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PWD}
      SPRING_DATASOURCE_URL: jdbc:mysql://docker-mysql/${DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true
    depends_on:
      - docker-mysql
    command:
      - mvn clean build
      - mvn clean spring-boot:run