CREATE TABLE GUEST(
  GUEST_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  FIRST_NAME VARCHAR(64),
  LAST_NAME VARCHAR(64),
  EMAIL_ADDRESS VARCHAR(64),
  ADDRESS VARCHAR(64),
  COUNTRY VARCHAR(32),
  STATE VARCHAR(12),
  PHONE_NUMBER VARCHAR(24)
);

CREATE TABLE TICKET(
  TICKET_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  GUEST_ID BIGINT NOT NULL,
  ITERNARY VARCHAR(64) NOT NULL
);